### PR TITLE
updating host.json to support bundles

### LINKED ISSUE #108: Change template so Azure Functions bundles work
We are removing the requirement of having .NET Core SDK installed to use extensions with functions.  To use this, instead of doing `func extensions install` you can have a `host.json` that includes bundling information.  The runtime can than use pre-built extensions automatically without requiring a .NET build.

We should update the archetype template to include this.

```json
{
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
        }
}
```

### PR DESCRIPTION
**Pull request by jeffhollan**
resolves #108

### CODE REVIEW

**Comment by mattchenderson** [comment]
We should hold on merging this until a few other bundles dependencies have come together.

**Comment by pragnagopa** [comment]
cc @amamounelsayed 
@soninaren - can you please take a look?

**Comment by pragnagopa** [comment]
@kulkarnisonia16

**Comment by pragnagopa** [comment]
@Flanker32 and @jdneo - Can you please look into this? Let us know if you need us open a separate issue.  This is needed to improve getting started experience with extenstion bundles

**Comment by Flanker32** [comment]
@pragnagopa We have added the support for bundle in maven plugin.

@mattchenderson Does bundles dependencies ready now and is the pr ready to merge?

**Comment by pragnagopa** [comment]
No blockers! Please go ahead and make this change

**Pull request merged**
