### PR TITLE
adding the version property to default host.json

### PR DESCRIPTION
**Pull request by brettsam**
With PR https://github.com/Azure/azure-functions-host/pull/3320, we'll require a 'version' property in the host.json. We want to make sure that new host.json creations include this by default.

### CODE REVIEW

**Comment by pragnagopa** [comment]
@jdneo - This is a breaking change in the upcoming functions release. If azure-maven-plugins creates a host.json file, then that needs to be updated as well. Can you please confirm?

**Comment by jdneo** [comment]
May I ask what's the difference between the version defined in `host.json` and that defined in the Application Settings (`FUNCTIONS_EXTENSION_VERSION`)?

**Comment by pragnagopa** [comment]
FUNCTIONS_EXTENSION_VERSION is for Functions runtime version. Version in host.json is for specifying json schema version for host.json

**Comment by brettsam** [comment]
This is a good question, though. Using `version` here may be confusing. @fabiocav / @paulbatum -- should we rename the property in host.json to `schemaVersion` to avoid confusion?

**Comment by jdneo** [comment]
@brettsam @paulbatum @pragnagopa 

So I guess we have achieved the conclusion that we will use `version` in the `host.json`, right?

Just trying to make sure we are good to merge this change.

**Comment by fabiocav** [comment]
@jdneo that's correct. We're moving forward with `version`

**Comment by jdneo** [comment]
@fabiocav Thanks for the confirmation.

**Pull request merged**
