### PR TITLE
Change the default HTTP trigger name to HttpExample

### PR DESCRIPTION
**Pull request by ggailey777**
@pragnagopa and @kulkarnisonia16 this PR updates the HTTP triggered function name to align Java with the other quickstarts and lets us add a Java pivot in the existing quickstarts. It also switches the default to ANONYMOUS auth, which UX testing has shown to be more successful in quickstarts, and we now use in the others.

### CODE REVIEW

**Comment by amamounelsayed** [comment]
Thank you so much @pragnagopa 
@ggailey777 Thank you so much for the update, the changes makes totally sense to me but for the ANONYMOUS we need to have @kulkarnisonia16 opinion before we merge. She will be back early next week and we still have time before the next build.

**Comment by ggailey777** [comment]
Thanks @amamounelsayed will look for it then.

**Comment by Flanker32** [comment]
@amamounelsayed  do we need to change the default value for AuthLevel in `azure-functions-java-library`?

**Comment by amamounelsayed** [comment]
Thank you @Flanker32 for bringing it up. I was thinking about the same point but no idea how this will impact the logic apps. I believe changing the default in the library it may not be safe.

**Comment by amamounelsayed** [comment]
@Flanker32 I do not think we can implement this feature at this current time.

**Comment by ggailey777** [comment]
This mostly impacts the Java quickstarts, which rely on the defaults in the archetype.

**Comment by kulkarnisonia16** [comment]
I think this makes sense specially having observed how folks struggle in UX studies following quick starts. @amamounelsayed - we should just be aware of any implications of this change. Thanks!

**Comment by amamounelsayed** [comment]
@kulkarnisonia16 changing the archetype is totally makes sense, if you are ok we just need to make sure that our guides and documentation will be aligned with it, if there is any. I believe the next build will be mid Feb. @ggailey777 Thank you so much for bring it up.

For updating the library this is different than this PR and it may not be safe to do it in the current time.

**Comment by Flanker32** [comment]
@yucwan Please help check is there any documents will be affected or need to be updated, so that we could finish this pr, thanks!

**Comment by yucwan** [comment]
I will update the doc here:
https://docs.microsoft.com/azure/azure-functions/functions-create-first-java-maven

**Pull request merged**
