### PR TITLE
Remove App Setting FUNCTIONS_WORKER_RUNTIME

### PR DESCRIPTION
**Pull request by Flanker32**
Remove App Setting FUNCTIONS_WORKER_RUNTIME as maven plugin will default set it to `java`, for issue #71

### CODE REVIEW

**Comment by brunoborges** [comment]
@Flanker32 the kotlin archetype points to the plugin version `1.3.2`. Do you know if this version already has the default worker_runtime ?

**Comment by Flanker32** [comment]
> @Flanker32 the kotlin archetype points to the plugin version `1.3.2`. Do you know if this version already has the default worker_runtime ?

No, not yet, this will be released in 1.3.3

**Comment by brunoborges** [comment]
Can you please update the pr to also change the version of the plugin then? Once it's released, we can merge this

**Comment by Flanker32** [comment]
@brunoborges Updated, but in our release pipeline, we usually bump maven plugin version before end-game and release maven plugin and archetype together.

**Comment by Flanker32** [comment]
@brunoborges Azure Function Maven plugin 1.3.3 has released

**Pull request merged**
